#line 2 "/home/drew/projects/SPL2EVPath/lex.yy.c"

#line 4 "/home/drew/projects/SPL2EVPath/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 162
#define YY_END_OF_BUFFER 163
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[428] =
    {   0,
        0,    0,    0,    0,  151,  151,    0,    0,  163,  162,
      160,  161,  133,  138,  137,   83,   85,   73,   74,   81,
       79,   78,   80,   77,   82,  158,  134,  126,   91,  113,
       93,  135,  137,   75,   76,   86,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  131,   87,  132,  149,  140,
      139,  162,  151,  153,  152,  156,  157,   95,  137,  116,
       88,  121,  114,  124,  117,  125,  118,    0,  101,  104,
       99,   97,   98,  100,  159,  108,    0,  110,  105,  159,
      106,  150,  155,  115,  159,  158,  158,  136,   84,   90,

       94,   92,    0,  137,  122,  137,   12,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,   36,   39,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  123,
       89,  149,  148,  141,  142,  146,  147,  143,  145,  144,
      151,  152,  152,  154,  112,  102,  107,  111,  109,  103,
      119,  120,  137,   20,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,   38,  137,  137,
      137,  137,  137,  137,   29,  137,  137,  137,  137,  137,

      137,  137,  137,  137,  137,  137,  137,   33,  137,  137,
      137,  137,  137,  137,  137,  137,    2,  137,  137,  137,
      141,  142,  137,  137,   65,  137,  137,  137,  137,  137,
      137,  137,  137,   37,   24,  137,  137,  137,  137,  137,
      137,  137,  137,  137,   47,  137,   28,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,   44,  137,    9,  137,   68,
      137,  137,  141,   96,  137,  137,   41,  137,  137,  137,
      137,  129,  137,  137,  137,   45,   25,  137,   10,    5,
      137,   48,   49,   50,  137,   13,  137,  137,  137,  137,

      137,  137,  137,  137,    8,  137,  137,  137,  137,   17,
      137,  137,  137,  137,   35,  137,  137,  137,  137,   52,
       40,  137,  137,  137,  137,  137,  137,   11,  137,  137,
      137,  137,  137,  137,  137,   51,  137,  137,  137,  137,
      137,  137,  137,  137,    6,  137,    3,   43,  130,  137,
      127,    7,   34,  137,  137,  137,   53,   54,   55,   14,
      137,   46,  137,   22,  137,  137,   23,  137,   57,   58,
      137,  137,  137,   19,  137,   30,   16,   15,  137,   31,
      137,  137,  137,   66,  137,  128,   56,  137,  137,  137,
      137,  137,   42,  137,  137,  137,  137,  137,   71,   27,

      137,   72,  137,   18,   67,  137,   69,  137,   62,   63,
        4,  137,   59,   60,  137,  137,    1,   32,   64,   21,
       61,   70,  137,  137,  137,   26,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   17,   22,   17,   23,   24,   25,   26,   27,
       28,   29,   30,    1,   31,   31,   31,   32,   33,   31,
       31,   31,   34,   31,   31,   35,   31,   31,   31,   36,
       31,   31,   31,   37,   31,   31,   31,   31,   31,   31,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   31,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[71] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    5,    5,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    5,    1,    3,    1,
        1,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[436] =
    {   0,
        0,    0,   68,   69,   72,   73,  577,  576,  578,  581,
      581,  581,  549,  581,    0,  548,   69,  581,  581,  547,
       66,  581,   65,  105,   70,  160,  549,  581,   60,  545,
       61,  581,  538,  581,  581,  543,   40,   43,  514,  522,
       27,   88,  509,   55,   55,   42,   75,   81,  102,  520,
      101,  134,   54,  510,  106,  581,  102,  581,    0,  581,
      581,  208,    0,  581,  104,  581,  581,  581,    0,  581,
      581,  581,  581,  581,  581,  581,  581,  537,  581,  581,
      581,  581,  581,  581,  253,  132,  536,  144,  581,  159,
      581,  581,  581,  581,    0,    0,  189,  581,  535,  581,

      581,  581,  534,  526,  581,  494,    0,  498,  502,  501,
      509,  133,  510,  494,  491,  495,  498,  494,  490,  493,
      504,    0,   78,  486,  496,  487,  482,  488,  487,  153,
      493,  493,  477,  478,  485,  491,  473,  472,  465,  111,
      477,  468,  472,  471,  472,  479,  474,  473,  468,  581,
      581,    0,  581,  261,  269,  581,  581,  581,  581,  581,
        0,  131,  181,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  490,    0,  462,  476,  466,  475,  464,  459,
      154,  464,  467,  459,  453,  451,  467,    0,  464,  451,
      445,  218,  445,  454,    0,  461,  456,  455,  439,  438,

      440,  451,  440,  453,  441,  441,  431,    0,  445,  430,
      144,  443,  442,  435,  440,  425,    0,  439,  431,  437,
      301,  309,  449,  430,    0,  433,  427,  431,  145,  426,
      415,  424,  420,    0,    0,  426,  425,  410,  409,  419,
      407,  224,  448,  445,    0,  416,    0,  419,  419,  402,
      402,  405,  402,  415,  398,  394,  401,  403,  402,  393,
      395,  197,  407,  394,  388,    0,  400,  400,  237,    0,
      398,  388,  317,    0,  399,  399,    0,  396,  393,  379,
      389,    0,  382,  393,  375,    0,  244,  383,    0,    0,
      410,    0,    0,    0,  373,    0,  378,  373,  378,  383,

      374,  365,  378,  363,    0,  362,  377,  366,  372,  371,
      373,  363,  367,  354,    0,  367,  239,  394,  391,    0,
        0,  347,  348,  354,  347,  342,  355,    0,  343,  351,
      343,  383,  380,  345,  343,    0,  355,  350,  353,  350,
      333,  346,  336,  345,    0,  339,    0,    0,    0,  327,
        0,    0,  176,  345,  339,  363,    0,    0,    0,    0,
      324,    0,  333,  146,  322,  335,  276,  330,    0,    0,
      331,  324,  325,    0,  332,    0,    0,    0,  314,    0,
      307,  315,  337,    0,  304,    0,    0,  269,  258,  293,
      289,  262,    0,  289,  288,  284,  248,  245,    0,    0,

      253,    0,  221,    0,    0,  205,    0,  199,    0,    0,
        0,  227,    0,    0,  190,  178,    0,    0,    0,    0,
        0,    0,  165,  156,  115,    0,  581,  341,  346,  351,
       86,  356,  361,  366,  371
    } ;

static yyconst flex_int16_t yy_def[436] =
    {   0,
      427,    1,  428,  428,  429,  429,  430,  430,  427,  427,
      427,  427,  427,  427,  431,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  431,  427,  427,  427,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  427,  427,  427,  432,  427,
      427,  433,  434,  427,  435,  427,  427,  427,  431,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,   85,   26,  427,  427,  427,  427,

      427,  427,  427,  431,  427,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  427,
      427,  432,  427,  427,  427,  427,  427,  427,  427,  427,
      434,  435,  435,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,

      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      427,  427,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  427,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,

      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,

      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,    0,  427,  427,  427,
      427,  427,  427,  427,  427
    } ;

static yyconst flex_int16_t yy_nxt[652] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   26,   26,   26,
       26,   26,   26,   26,   27,   28,   29,   30,   31,   32,
       15,   15,   15,   15,   15,   15,   33,   34,   10,   35,
       36,   10,   37,   38,   39,   40,   41,   42,   43,   15,
       44,   15,   45,   46,   47,   48,   49,   15,   50,   51,
       52,   53,   54,   55,   15,   15,   15,   56,   57,   58,
       60,   60,   61,   61,   64,   64,   71,   74,   76,  114,
       92,  115,   65,   65,  126,   93,   99,  100,  102,  103,
       69,  116,   77,   75,  106,  109,   72,   94,  110,  107,

      108,  111,  122,  127,  145,  124,   62,   62,   78,  123,
      125,   79,   80,  146,  163,   81,   82,  128,   83,  164,
       84,   85,   85,   85,   85,   85,   85,   85,   85,  150,
      117,   86,   87,   88,  191,  130,  129,  131,  192,  132,
      118,  427,  133,  119,  134,   89,  427,  138,   90,  120,
       90,  139,   90,  210,   90,  148,  149,   90,  166,  167,
      135,  140,   90,  136,   90,  390,   90,  391,   90,  211,
      151,  169,  170,   91,   95,  426,   96,   96,   96,   96,
       96,   96,   96,   96,  141,  179,  180,  181,  199,  200,
      263,  163,  142,  383,  264,  143,  164,  279,  384,  144,

      280,  230,   90,   97,   90,   97,   90,   97,   90,   97,
      425,   90,   97,  231,  232,  424,   90,   97,   90,   97,
       90,   97,   90,   97,  154,  154,  154,  154,  154,  154,
      155,  155,   97,  423,   97,  242,   97,  243,   97,  244,
      245,   97,  291,  310,  422,  292,   97,  311,   97,  421,
       97,  156,   97,  420,  317,  157,  318,  356,  319,  320,
      357,  419,  158,  332,  246,  333,  159,  418,  160,   85,
       85,   85,   85,   85,   85,   85,   85,  221,  221,  221,
      221,  221,  221,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  394,  334,  395,   90,  396,   90,  417,

       90,  416,   90,  415,  414,   90,  413,  412,  411,  410,
       90,  409,   90,  408,   90,  407,   90,  273,  273,  273,
      273,  273,  273,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,   59,   59,   59,   59,   59,   63,   63,   63,   63,
       63,   66,   66,   66,   66,   66,  152,  406,  405,  152,
      152,  153,  153,  153,  153,  153,  161,  404,  161,  403,
      161,  162,  402,  162,  162,  162,  401,  400,  399,  398,
      397,  393,  392,  389,  388,  387,  386,  385,  382,  381,
      380,  379,  378,  377,  376,  375,  374,  373,  372,  371,

      370,  369,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  359,  358,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  331,  330,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  316,  315,  314,  313,  312,
      309,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  278,  277,  276,
      275,  274,  272,  271,  270,  269,  268,  267,  266,  265,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,

      252,  251,  250,  249,  248,  247,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  229,  228,  227,  226,  225,
      224,  223,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      198,  197,  196,  195,  194,  193,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  178,  177,  176,  175,  174,
      173,  172,  171,  168,  165,  147,  137,  121,  113,  112,
      105,  104,  101,   98,   73,   70,   68,  427,   67,   67,
        9,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,

      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427
    } ;

static yyconst flex_int16_t yy_chk[652] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    3,    4,    5,    6,   17,   21,   23,   41,
       25,   41,    5,    6,   46,   25,   29,   29,   31,   31,
      431,   41,   23,   21,   37,   38,   17,   25,   38,   37,

       37,   38,   44,   46,   53,   45,    3,    4,   24,   44,
       45,   24,   24,   53,   65,   24,   24,   47,   24,   65,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   57,
       42,   24,   24,   24,  123,   48,   47,   48,  123,   48,
       42,  162,   48,   42,   49,   24,  162,   51,   24,   42,
       24,   51,   24,  140,   24,   55,   55,   24,   86,   86,
       49,   51,   24,   49,   24,  364,   24,  364,   24,  140,
       57,   88,   88,   24,   26,  425,   26,   26,   26,   26,
       26,   26,   26,   26,   52,  112,  112,  112,  130,  130,
      211,  163,   52,  353,  211,   52,  163,  229,  353,   52,

      229,  181,   90,   26,   90,   26,   90,   26,   90,   26,
      424,   90,   26,  181,  181,  423,   90,   26,   90,   26,
       90,   26,   90,   26,   62,   62,   62,   62,   62,   62,
       62,   62,   97,  416,   97,  192,   97,  192,   97,  192,
      192,   97,  242,  262,  415,  242,   97,  262,   97,  412,
       97,   62,   97,  408,  269,   62,  269,  317,  269,  269,
      317,  406,   62,  287,  192,  287,   62,  403,   62,   85,
       85,   85,   85,   85,   85,   85,   85,  154,  154,  154,
      154,  154,  154,  154,  154,  155,  155,  155,  155,  155,
      155,  155,  155,  367,  287,  367,   85,  367,   85,  401,

       85,  398,   85,  397,  396,   85,  395,  394,  392,  391,
       85,  390,   85,  389,   85,  388,   85,  221,  221,  221,
      221,  221,  221,  221,  221,  222,  222,  222,  222,  222,
      222,  222,  222,  273,  273,  273,  273,  273,  273,  273,
      273,  428,  428,  428,  428,  428,  429,  429,  429,  429,
      429,  430,  430,  430,  430,  430,  432,  385,  383,  432,
      432,  433,  433,  433,  433,  433,  434,  382,  434,  381,
      434,  435,  379,  435,  435,  435,  375,  373,  372,  371,
      368,  366,  365,  363,  361,  356,  355,  354,  350,  346,
      344,  343,  342,  341,  340,  339,  338,  337,  335,  334,

      333,  332,  331,  330,  329,  327,  326,  325,  324,  323,
      322,  319,  318,  316,  314,  313,  312,  311,  310,  309,
      308,  307,  306,  304,  303,  302,  301,  300,  299,  298,
      297,  295,  291,  288,  285,  284,  283,  281,  280,  279,
      278,  276,  275,  272,  271,  268,  267,  265,  264,  263,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  246,  244,  243,  241,  240,  239,
      238,  237,  236,  233,  232,  231,  230,  228,  227,  226,
      224,  223,  220,  219,  218,  216,  215,  214,  213,  212,
      210,  209,  207,  206,  205,  204,  203,  202,  201,  200,

      199,  198,  197,  196,  194,  193,  191,  190,  189,  187,
      186,  185,  184,  183,  182,  180,  179,  178,  177,  176,
      175,  173,  149,  148,  147,  146,  145,  144,  143,  142,
      141,  139,  138,  137,  136,  135,  134,  133,  132,  131,
      129,  128,  127,  126,  125,  124,  121,  120,  119,  118,
      117,  116,  115,  114,  113,  111,  110,  109,  108,  106,
      104,  103,   99,   87,   78,   54,   50,   43,   40,   39,
       36,   33,   30,   27,   20,   16,   13,    9,    8,    7,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,

      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "spl.l"
#line 2 "spl.l"
static	int lex_offset = 1;
static  int line_count = 1;
static char *create_string_from_yytext();
#define RETURN(val) {yylval.info.lx_srcpos.line = line_count; yylval.info.lx_srcpos.character = lex_offset; lex_offset +=yyleng; return(val);}
static int type_count;
static char**types;
#ifdef input
/* lex, not flex */
static char *saved_input_str = NULL;
static void 
terminate_string_parse()
{
    if (saved_input_str) {
	free(saved_input_str);
        saved_input_str = NULL;
    }
}

static char *input_str = NULL;
static void
setup_for_string_parse(string, defined_type_count, defined_types)
char *string;
int defined_type_count;
char **defined_types;
{
    int len = strlen(string);

    type_count = defined_type_count;
    types = defined_types;
    if (saved_input_str != NULL) free(input_str);
    input_str = malloc(len + 2);
    saved_input_str = input_str;
    strcpy(input_str, string);
    input_str[len] = 0;
    input_str[len + 1] = 0;
    lex_offset = 1;
    line_count = 1;
}
#undef input
#define input() (((yytchar=*input_str)==0)?0:(input_str++,yytchar==10?(yylineno++,yytchar):yytchar))
#undef unput
#define unput(c) (input_str--,c==10?yylineno--:yylineno)
#else
/* flex */

#ifdef YY_INPUT
#undef YY_INPUT
extern int my_yy_input();
#define YY_INPUT(buf,x,y) x=my_yy_input(buf,x,y)
#endif

/* end of lex ifdef */
#endif
static
int
is_defined_type(id)
char *id;
{
    int i;
    for(i=0; i< type_count; i++) {
	if (strcmp(id, types[i]) == 0) return 1;
    }
    return 0;
}
static void check_strbuf();
static int buffer_len;
static char *string_buffer;
static char *string_buf_ptr;

#line 817 "/home/drew/projects/SPL2EVPath/lex.yy.c"

#define INITIAL 0
#define string_cond 1
#define comment 2
#define slash_comment 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 73 "spl.l"


#line 1010 "/home/drew/projects/SPL2EVPath/lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 428 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 581 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 75 "spl.l"
{RETURN(NAMESPACE);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 76 "spl.l"
{RETURN(USE);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 77 "spl.l"
{RETURN(PUBLIC);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 78 "spl.l"
{RETURN(COMPOSITE);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 79 "spl.l"
{RETURN(INPUT);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 80 "spl.l"
{RETURN(OUTPUT);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 81 "spl.l"
{RETURN(STREAM);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 82 "spl.l"
{RETURN(PARAM);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 83 "spl.l"
{RETURN(TYPE);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 84 "spl.l"
{RETURN(GRAPH);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 85 "spl.l"
{RETURN(CONFIG);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 86 "spl.l"
{RETURN(AS);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 87 "spl.l"
{RETURN(LOGIC);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 88 "spl.l"
{RETURN(WINDOW);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 89 "spl.l"
{RETURN(ONTUPLE);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 90 "spl.l"
{RETURN(ONPUNCT);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 91 "spl.l"
{RETURN(STATE);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 92 "spl.l"
{RETURN(STATEFUL);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 93 "spl.l"
{RETURN(MUTABLE);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 94 "spl.l"
{RETURN(ANY);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 95 "spl.l"
{RETURN(COLLECTION);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 96 "spl.l"
{RETURN(COMPLEX);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 97 "spl.l"
{RETURN(DECIMAL);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 98 "spl.l"
{RETURN(ENUM);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 99 "spl.l"
{RETURN(FLOAT);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 100 "spl.l"
{RETURN(FLOATINGPOINT);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 101 "spl.l"
{RETURN(INTEGRAL);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 102 "spl.l"
{RETURN(LIST);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 103 "spl.l"
{RETURN(MAP);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 104 "spl.l"
{RETURN(NUMERIC);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 105 "spl.l"
{RETURN(ORDERED);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 106 "spl.l"
{RETURN(PRIMITIVE);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 107 "spl.l"
{RETURN(SET);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 108 "spl.l"
{RETURN(STRING);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 109 "spl.l"
{RETURN(TUPLE);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 110 "spl.l"
{RETURN(IF);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 111 "spl.l"
{RETURN(ELSE);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 112 "spl.l"
{RETURN(FOR);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 113 "spl.l"
{RETURN(IN);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 114 "spl.l"
{RETURN(WHILE);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 115 "spl.l"
{RETURN(BREAK);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 116 "spl.l"
{RETURN(CONTINUE);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 117 "spl.l"
{RETURN(RETURN_TOKEN);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 118 "spl.l"
{RETURN(TRUE);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 119 "spl.l"
{RETURN(FALSE);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 120 "spl.l"
{RETURN(BOOLEAN);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 121 "spl.l"
{RETURN(INT8);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 122 "spl.l"
{RETURN(INT16);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 123 "spl.l"
{RETURN(INT32);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 124 "spl.l"
{RETURN(INT64);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 125 "spl.l"
{RETURN(INT128);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 126 "spl.l"
{RETURN(UINT8);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 127 "spl.l"
{RETURN(UINT16);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 128 "spl.l"
{RETURN(UINT32);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 129 "spl.l"
{RETURN(UINT64);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 130 "spl.l"
{RETURN(UINT128);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 131 "spl.l"
{RETURN(FLOAT32);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 132 "spl.l"
{RETURN(FLOAT64);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 133 "spl.l"
{RETURN(DECIMAL32);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 134 "spl.l"
{RETURN(DECIMAL64);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 135 "spl.l"
{RETURN(DECIMAL128);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 136 "spl.l"
{RETURN(COMPLEX32);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 137 "spl.l"
{RETURN(COMPLEX64);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 138 "spl.l"
{RETURN(TIMESTAMP);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 139 "spl.l"
{RETURN(BLOB);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 140 "spl.l"
{RETURN(STRING8);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 141 "spl.l"
{RETURN(STRING16);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 142 "spl.l"
{RETURN(VOID);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 143 "spl.l"
{RETURN(ATTRIBUTE);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 144 "spl.l"
{RETURN(EXPRESSION);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 145 "spl.l"
{RETURN(FUNCTION);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 146 "spl.l"
{RETURN(OPERATOR);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 148 "spl.l"
{RETURN(LPAREN);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 149 "spl.l"
{RETURN(RPAREN);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 150 "spl.l"
{RETURN(LBRACKET);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 151 "spl.l"
{RETURN(RBRACKET);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 152 "spl.l"
{RETURN(DOT);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 153 "spl.l"
{RETURN(COMMA);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 155 "spl.l"
{RETURN(PLUS);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 156 "spl.l"
{RETURN(MINUS);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 157 "spl.l"
{RETURN(STAR);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 158 "spl.l"
{RETURN(SLASH);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 159 "spl.l"
{RETURN(MODULUS);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 160 "spl.l"
{RETURN(LEFT_SHIFT);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 161 "spl.l"
{RETURN(ARITH_AND);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 162 "spl.l"
{RETURN(ARITH_XOR);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 163 "spl.l"
{RETURN(ARITH_OR);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 164 "spl.l"
{RETURN(LOG_AND);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 165 "spl.l"
{RETURN(LOG_OR);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 166 "spl.l"
{RETURN(LEQ);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 167 "spl.l"
{RETURN(LT);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 168 "spl.l"
{RETURN(GEQ);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 169 "spl.l"
{RETURN(*yytext);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 170 "spl.l"
{RETURN(EQ);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 171 "spl.l"
{RETURN(NEQ);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 173 "spl.l"
{RETURN(TILDE);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 175 "spl.l"
{RETURN(DOT_PLUS);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 176 "spl.l"
{RETURN(DOT_MINUS);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 177 "spl.l"
{RETURN(DOT_STAR);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 178 "spl.l"
{RETURN(DOT_SLASH);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 179 "spl.l"
{RETURN(DOT_MODULUS);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 180 "spl.l"
{RETURN(DOT_LEFT_SHIFT);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 181 "spl.l"
{RETURN(DOT_RIGHT_SHIFT);}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 182 "spl.l"
{RETURN(DOT_ARITH_AND);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 183 "spl.l"
{RETURN(DOT_ARITH_XOR);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 184 "spl.l"
{RETURN(DOT_ARITH_OR);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 185 "spl.l"
{RETURN(DOT_LEQ);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 186 "spl.l"
{RETURN(DOT_LT);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 187 "spl.l"
{RETURN(DOT_GEQ);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 188 "spl.l"
{RETURN(DOT_GT);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 189 "spl.l"
{RETURN(DOT_EQ);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 190 "spl.l"
{RETURN(DOT_NEQ);}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 192 "spl.l"
{RETURN(ASSIGN);}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 193 "spl.l"
{RETURN(MUL_ASSIGN);}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 194 "spl.l"
{RETURN(DIV_ASSIGN);}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 195 "spl.l"
{RETURN(MOD_ASSIGN);}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 196 "spl.l"
{RETURN(ADD_ASSIGN);}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 197 "spl.l"
{RETURN(SUB_ASSIGN);}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 198 "spl.l"
{RETURN(LEFT_ASSIGN);}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 199 "spl.l"
{RETURN(RIGHT_ASSIGN);}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 200 "spl.l"
{RETURN(AND_ASSIGN);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 201 "spl.l"
{RETURN(XOR_ASSIGN);}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 202 "spl.l"
{RETURN(OR_ASSIGN);}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 203 "spl.l"
{RETURN(INC_OP);}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 204 "spl.l"
{RETURN(DEC_OP);}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 205 "spl.l"
{RETURN(SEMI);}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 206 "spl.l"
{RETURN(STATIC);}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 207 "spl.l"
{RETURN(TYPEDEF);}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 208 "spl.l"
{RETURN(CONST);}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 209 "spl.l"
{RETURN(SIZEOF);}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 210 "spl.l"
{RETURN(LCURLY);}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 211 "spl.l"
{RETURN(RCURLY);}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 212 "spl.l"
{RETURN(BANG);}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 213 "spl.l"
{RETURN(COLON);}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 214 "spl.l"
{RETURN(QUESTION);}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 215 "spl.l"
{RETURN(COLON_COLON);}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 216 "spl.l"
{
				yylval.info.string = create_string_from_yytext();
				RETURN(identifier_ref);
				}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 221 "spl.l"
{
	  buffer_len = 20;
	  string_buffer = malloc(20);
	  string_buf_ptr = string_buffer; BEGIN(string_cond);
}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 227 "spl.l"
{ /* saw closing quote - all done */
        BEGIN(INITIAL);
        *string_buf_ptr = '\0';
        /* return string constant token type and
         * value to parser
         */
	yylval.info.string = string_buffer;
	RETURN(string_constant);
}
	YY_BREAK
case 140:
/* rule 140 can match eol */
YY_RULE_SETUP
#line 237 "spl.l"
{
	yyerror("Unterminated string constant");
}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 241 "spl.l"
{
        /* octal escape sequence */
        int result;

        (void) sscanf( yytext + 1, "%o", &result );

        if ( result > 0xff ) {
	   yyerror("bad octal escape character");
	}

        check_strbuf();
	*string_buf_ptr++ = result;
}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 255 "spl.l"
{
	 yyerror("bad character escape");
}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 259 "spl.l"
{check_strbuf();*string_buf_ptr++ = '\n';}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 260 "spl.l"
{check_strbuf();*string_buf_ptr++ = '\t';}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 261 "spl.l"
{check_strbuf();*string_buf_ptr++ = '\r';}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 262 "spl.l"
{check_strbuf();*string_buf_ptr++ = '\b';}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 263 "spl.l"
{check_strbuf();*string_buf_ptr++ = '\f';}
	YY_BREAK
case 148:
/* rule 148 can match eol */
YY_RULE_SETUP
#line 265 "spl.l"
{check_strbuf();*string_buf_ptr++ = yytext[1];}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 267 "spl.l"
{
        char *yptr = yytext;

        while ( *yptr ) {
		check_strbuf();
                *string_buf_ptr++ = *yptr++;
        }
}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 278 "spl.l"
BEGIN(comment);
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 280 "spl.l"
{lex_offset += yyleng;} /* eat anything that's not a '*' */
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 281 "spl.l"
{lex_offset += yyleng;} /* eat up '*'s not followed by '/'s */
	YY_BREAK
case 153:
/* rule 153 can match eol */
YY_RULE_SETUP
#line 282 "spl.l"
{++line_count;lex_offset = 1;}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 283 "spl.l"
{lex_offset += yyleng;BEGIN(INITIAL);}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 285 "spl.l"
BEGIN(slash_comment);
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 287 "spl.l"
{lex_offset += yyleng;} /* eat anything that's not a '\n' */
	YY_BREAK
case 157:
/* rule 157 can match eol */
YY_RULE_SETUP
#line 288 "spl.l"
{++line_count;lex_offset = 1;BEGIN(INITIAL);}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 291 "spl.l"
{
				yylval.info.string = create_string_from_yytext();
				RETURN(integer_constant);
			}
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 296 "spl.l"
{
				yylval.info.string = create_string_from_yytext();
				RETURN(floating_constant);
			}
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 301 "spl.l"
{lex_offset += yyleng;}
	YY_BREAK
case 161:
/* rule 161 can match eol */
YY_RULE_SETUP
#line 302 "spl.l"
{lex_offset = 1; line_count++;}
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 303 "spl.l"
ECHO;
	YY_BREAK
#line 1952 "/home/drew/projects/SPL2EVPath/lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(string_cond):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(slash_comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 428 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 428 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 427);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 303 "spl.l"


static char *create_string_from_yytext()
{
  char *st = (char *) malloc((yyleng+1)*sizeof(char));
  strcpy (st, yytext);
  return(st);
}

static void check_strbuf()
{
    int cur_len = string_buf_ptr - string_buffer;
    if ((cur_len + 1) == buffer_len) {
	buffer_len += 20;
	string_buffer = realloc(string_buffer, buffer_len);
	string_buf_ptr = string_buffer + cur_len;
    }
}

#define yy_size_t int
#ifndef yyconst
#define yyconst
#endif 

#if defined(__STDC__) || defined(__cplusplus) || defined(c_plusplus)
#define YY_USE_PROTOS
#endif

#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif

extern int
yywrap YY_PROTO(( void ))
{
    return 1;
}


#ifndef input
/* flex, not lex */
void yy_delete_buffer YY_PROTO((YY_BUFFER_STATE b));

#ifdef WINNT
/* old Windows code for MKS Toolkit version of flex */

static void 
terminate_string_parse()
{
    yyrestart(NULL);
}

#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

static char* current_input_string;

int my_yy_input(buf,result,max_size) {

      if (current_input_string == NULL) 
      {
           
           result = 0;
      }
      else
           if (max_size < strlen(current_input_string)) 
	   {
	        memcpy((void*)buf, current_input_string, max_size);
		current_input_string += max_size;
		result = max_size;
	   } else {
	        int n = strlen(current_input_string);
		memcpy((void*)buf, current_input_string, n+1);
		current_input_string = NULL;
		result = n;
	   }
      	  
/*      printf("my_yy_input buf[%s],result[%d]\n",buf,result);*/
      return result;
}

static void
setup_for_string_parse(string, defined_type_count, defined_types)
char *string;
int defined_type_count;
char **defined_types;
{
    type_count = defined_type_count;
    types = defined_types;

    current_input_string = string;
    lex_offset = 1;
    line_count = 1;
}
#else

static YY_BUFFER_STATE bb = NULL;

static void
reset_types_table(defined_type_count, defined_types)
int defined_type_count;
char **defined_types;
{
    type_count = defined_type_count;
    types = defined_types;
}

static void
setup_for_string_parse(string, defined_type_count, defined_types)
char *string;
int defined_type_count;
char **defined_types;
{
    type_count = defined_type_count;
    types = defined_types;

    if ((bb = yy_scan_string(string)) == NULL) {
       fprintf(stderr, "yyscan_buffer_failed\n");
     }
    lex_offset = 1;
    line_count = 1;
}

static void 
terminate_string_parse()
{
    if (bb) {
		yy_delete_buffer(bb);
		bb = NULL;
	}
}

#endif
#endif

