# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/drewbratcher/nightly_build_area/spl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/drewbratcher/nightly_build_area/spl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/drewbratcher/nightly_build_area/spl/CMakeFiles /Users/drewbratcher/nightly_build_area/spl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/drewbratcher/nightly_build_area/spl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named parse

# Build rule for target.
parse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parse
.PHONY : parse

# fast build rule for target.
parse/fast:
	$(MAKE) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/build
.PHONY : parse/fast

parse.o: parse.c.o
.PHONY : parse.o

# target to build an object file
parse.c.o:
	$(MAKE) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/parse.c.o
.PHONY : parse.c.o

parse.i: parse.c.i
.PHONY : parse.i

# target to preprocess a source file
parse.c.i:
	$(MAKE) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/parse.c.i
.PHONY : parse.c.i

parse.s: parse.c.s
.PHONY : parse.s

# target to generate assembly for a file
parse.c.s:
	$(MAKE) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/parse.c.s
.PHONY : parse.c.s

spl.tab.o: spl.tab.c.o
.PHONY : spl.tab.o

# target to build an object file
spl.tab.c.o:
	$(MAKE) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/spl.tab.c.o
.PHONY : spl.tab.c.o

spl.tab.i: spl.tab.c.i
.PHONY : spl.tab.i

# target to preprocess a source file
spl.tab.c.i:
	$(MAKE) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/spl.tab.c.i
.PHONY : spl.tab.c.i

spl.tab.s: spl.tab.c.s
.PHONY : spl.tab.s

# target to generate assembly for a file
spl.tab.c.s:
	$(MAKE) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/spl.tab.c.s
.PHONY : spl.tab.c.s

spl_node.o: spl_node.c.o
.PHONY : spl_node.o

# target to build an object file
spl_node.c.o:
	$(MAKE) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/spl_node.c.o
.PHONY : spl_node.c.o

spl_node.i: spl_node.c.i
.PHONY : spl_node.i

# target to preprocess a source file
spl_node.c.i:
	$(MAKE) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/spl_node.c.i
.PHONY : spl_node.c.i

spl_node.s: spl_node.c.s
.PHONY : spl_node.s

# target to generate assembly for a file
spl_node.c.s:
	$(MAKE) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/spl_node.c.s
.PHONY : spl_node.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... parse"
	@echo "... rebuild_cache"
	@echo "... parse.o"
	@echo "... parse.i"
	@echo "... parse.s"
	@echo "... spl.tab.o"
	@echo "... spl.tab.i"
	@echo "... spl.tab.s"
	@echo "... spl_node.o"
	@echo "... spl_node.i"
	@echo "... spl_node.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

